# Generated by Django 5.2.8 on 2025-12-01 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('red_social', models.CharField(blank=True, max_length=100)),
                ('descripcion_solicitud', models.TextField()),
                ('fecha_solicitada', models.DateField(blank=True, null=True)),
                ('plataforma', models.CharField(choices=[('WEB', 'Sitio Web'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('WSP', 'WhatsApp'), ('PRESENCIAL', 'Presencial'), ('OTRO', 'Otro')], default='WEB', max_length=20)),
                ('estado_pedido', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('REALIZADA', 'Realizada'), ('ENTREGADA', 'Entregada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='referencias_clientes/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_referencia', to='mainApp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.IntegerField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.producto'),
        ),
    ]
