# Generated by Django 4.2.27 on 2025-12-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
